[tool.poetry]
name = "data-pipelines"
version = "0.1.0"
description = "Data pipelines for the OpenEPI data platform"
authors = ["Aleksander Stangeland <aleksander.stangeland@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.25.2"
urllib3 = "1.26.15"
dagster = "^1.5.12"
dagster-webserver = "^1.5.12"
bokeh = "^3.3.2"
pyarrow = "^14.0.2"
dask = "^2023.12.0"
distributed = "^2023.12.0"
xarray = "^2023.12.0"
rioxarray = "^0.15.0"
rio-cogeo = "^5.1.0"
geopandas = "^0.14.1"
dask-geopandas = "^0.3.1"
zarr = "^2.16.1"


[tool.poetry.group.dev.dependencies]
black = "^23.12.0"
notebook = "^7.0.6"


[tool.dagster]
module_name = "data_pipelines"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
