apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dagster-webserver
  namespace: dagster
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/dagster`)
    services:
    - kind: Service
      name: dagster-dagster-webserver
      port: 80
